import Vapor
import Fluent
import FluentMySQLDriver

public class UserController {
    private func generateLoginCode() throws -> String {
        // dict is at /usr/share/dict/words
        let wordList = "/usr/share/dict/words"
        var loginCode = ""

        do {
            // parse word list and convert to array
            let rawString = try String(contentsOfFile: wordList)
            var arrayOfWords = rawString.split(separator: "\n")

            // prevent insecure codes from being generated by removing short words
            arrayOfWords.removeAll(where: {$0.count < 4})

            // randomly choose 4 words
            for _ in stride(from: 0, to: 4, by: 1) {
                loginCode += arrayOfWords[Int.random(in:0..<arrayOfWords.count)] + " "
            }
            
        } catch {
            print(error)
        }

        return loginCode.removeLast()
    }
}
